devicemanage/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mobiledevice/',include('mobiledevice.urls')),
    path('createdatabase/',include('createdatabase.urls')),
]
urlpatterns += static('/media/', document_root=settings.MEDIA_ROOT)

createdatabase/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Users(models.Model):
    user_name=models.CharField('用户名',max_length=64,default='guest')
    password=models.CharField(max_length=64)
    role=models.CharField(max_length=32,default=2) #0代表超级管理员，1代表普通管理员，2代表guest
    registe_time=models.DateTimeField(auto_now=True)
    login_time=models.CharField(max_length=64,default='Null')
    icon=models.CharField(max_length=64,default='/icon/default.png') #用户头像地址
    session=models.CharField(max_length=64) #登录后生产的随机字符串
    comments=models.CharField(max_length=64,default='游客')
    login_name=models.CharField(max_length=64,default='Null')

    class Meta:
        db_table = 'users'

    def __unicode__(self):
            return self.user_name

    def __str__(self):
        return self.user_name

class Devices(models.Model):
    id=models.AutoField(primary_key=True)
    device_name=models.CharField(max_length=64) #设备名
    model=models.CharField(max_length=64,default='Null') #设备型号
    theNum=models.CharField(max_length=64)            #设备编号
    plateform=models.CharField(max_length=64,default='Null') #平台android或者ios
    brand=models.CharField(max_length=64,null=True) #品牌
    owner=models.CharField(max_length=64,default='测试')#分配出去的设备，行政借给谁了
    status=models.CharField(max_length=64,default=1)# 1:未借出的状态；2：借出；0：申请中
    borrower=models.CharField(max_length=64,null=True)#借阅者
    UUID=models.CharField(max_length=64,null=True)#设备的UUID
    comments=models.CharField(max_length=64,null=True)#备注
    category=models.CharField(max_length=64,default='Null')#设备分类
    check_dev=models.CharField(max_length=64,default=0)#盘点设备的字段,0是未盘点，1是已盘点
    version = models.CharField(max_length=64, default='Null')#系统版本
    old_dev=models.CharField(max_length=64,default=0)#0表示设备是好的，1表示设备报废
    add_time=models.DateTimeField(auto_now_add=True) #添加设备的时间
    borrow_time=models.CharField(max_length=32,null=True)#借出设备的时间

    class Meta:
        db_table = 'devices'

    def __unicode__(self):
            return self.device_name

    def __str__(self):
        return self.device_name

class Dev_imgs(models.Model):
    device_id=models.ForeignKey('Devices',to_field='id',on_delete=models.CASCADE,default='Null')
    path=models.ImageField("图片",blank=True)
    apply_path=models.ImageField("申请采购图片",blank=True)

    class Meta:
        db_table = 'dev_imgs'

    def get_absolute_url(self):
        return reverse('pic_upload:pic_detail', args=[str(self.id)])

    def __unicode__(self):
        return self.device_id

    def __str__(self):
        return self.device_id

templates/aboutPage.html
{% extends "base.html" %}
{% load static %}
{% block title %}关于系统{% endblock %}
{% block link %}<link href="{%static 'devMS/css/aboutPage/aboutPage.css'%}" rel="stylesheet"/>{% endblock %}
{% block contend %}

    <div style="width: 100%;height:100%;background-color:#EEEEFF">

{#        <div style="width: 100%;height:200px;background-color:#EEEEFF"></div>#}
        <div style="width: 100%;height:200px;background-color:#EEEEFF;text-align:center;">
            <h3 style="margin-top:0px;margin-bottom:20px;">亲，喜欢就点个赞吧~</h3>
            <img id="like-btn" src="/media/click_on.png"></img>
        </div>
        <div>
            <h4 id="like" style="text-align:center;margin-top:30px;" hidden>O(∩_∩)O   Thanks you ~</h4>
            <div style="text-align:center;padding-top:20px;" target="_blank"><label>本系统采用Django 2.2&Python3.7.2<a href=""></a></label>
            </div>
            <div style="text-align:center;padding-top:20px;"><label style="margin-top:0px;margin-bottom:20px;" >设备管理系统--Version1.2~</label>
            </div>
            <hr style="background-color:#333;text-align:center;padding-top:1px;" />
            <div style="text-align:center;padding-top:20px;">
                <label style="margin-top:0px;margin-bottom:20px;" >release note--Version1.1~</label>
                <p style="text-align:left;margin-top:0px;margin-bottom:20px;" >1.添加了借用、修改系统版本提醒</p>
            </div>
             <div style="text-align:center;padding-top:20px;">
                 <label style="margin-top:0px;margin-bottom:20px;" >release note--Version1.2~</label>
                 <p style="text-align:left;margin-top:0px;margin-bottom:20px;" >1.设备增加采购报告
                                    2.搜索框模糊搜索
                                    3.增加一键导出设备到excel
                                    4.增加日志 设备型号
                                    5.修改bug，修改按钮提示系统版本为null
                                    6.添加分页功能  
                 </p>
            </div>
        </div>
   </div>
{% endblock %}

templates/adddevice.html
{% extends "base.html" %}
{% load static %}
{% block title %} 设备管理添加页{% endblock %}
{% block link %}<link href="{%static 'devMS/css/addDevices/addDevices.css'%}" rel="stylesheet"/>{% endblock %}

{% block contend %}
    <div id="add_devices">
        <form action="/mobiledevice/adddevice/" method="post" enctype="multipart/form-data">
            <table>
                {{ deviceform.as_table }}
            </table>
             <p style="margin-left:300px;">
                 <input type="submit" value="添加" style="margin-left:10px;position:absolute;padding-top:5px;color: #2a6496">
                 <input type="reset" value="取消" style="margin-left:200px;position:absolute;padding-top:5px;color: #2a6496" name="reset">
             </p>
        </form>

    </div>

{% endblock %}
{% block js %}
 <script src="{% static 'devMS/js/addDevices/addDevices.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'devMS/css/index.css' %}" rel="stylesheet">
    {% block link %} {% endblock %}

</head>
<body>
    <div id="main">
        <div id="top_bar">
            <label style="color:white;font-size:20px;margin-left:45px;margin-top:8px;">设备管理系统</label>
            <div>
                <label class="login_label"><a href="/mobiledevice/logout/">退出</a></label>
                <label class="welcome_label" >welcome~{{ request.session.username }}</label>
            </div>
        </div>

        <div style="width: 100%;height:100%;">
            <div id="left_item">
                <div class="setting_item"><label id = "searchDevices" class="setting_label" onclick="changeMenu(event)">设 备 查 询</label></div>
                <div class="setting_item"><label id = "addDevices"  class="setting_label" onclick="changeMenu(event)">添 加 设 备</label></div>
                <div class="setting_item"><label id = "manDevices"  class="setting_label" onclick="changeMenu(event)" >管 理 设 备</label></div>
                <div class="setting_item"><label id = "checkDevices"  class="setting_label" onclick="changeMenu(event)">设 备 盘 点</label></div>
                <div class="setting_item"><label id = "logMan" class="setting_label" onclick="changeMenu(event)">日 志 管 理</label></div>
                <div class="setting_item"><label id = "aboutPage"  class="setting_label" onclick="changeMenu(event)">关 于 系 统</label></div>
            </div>
            <div id="right_content">
            {% block contend %}
            {% endblock %}
            </div>
        </div>
    </div>

    <script src="{% static 'devMS/js/jquery-3.1.1.min.js'%}"></script>
    <script src="{% static 'devMS/js/jquery.cookie.js'%}"></script>
    <script src="{% static 'devMS/js/index.js'%}"></script>
    {% block js %}

    {% endblock %}

</body>
</html>

templates/checkdevice.html
{% extends "base.html" %}
{% load static %}
{% block title %}盘点设备{% endblock %}
{% block link %}<link href="{% static 'devMS/css/checkDevices/checkDevices.css' %}" rel="stylesheet">{% endblock %}

{% block contend %}
<div id="search_area">
    <div style="text-align: center;padding-top:10px;">
	<button type="button" class="btn btn-sm btn-primary" style="margin-right: 20px;" id="no_checked" onclick="getNoCheckedDevs()">未盘点</button>
	<button type="button" class="btn btn-sm btn-success" style="margin-right: 20px;" id="checkeded" onclick="getCheckedDevs()">已盘点</button>
	<button type="button" class="btn btn-sm btn-info" style="margin-right: 20px;" id="all_devs" onclick="getAllDevs()">所有</button>
	<button type="button" class="btn btn-sm btn-danger" style="margin-right: 20px;" id="initaillize" onclick="initaillizeDevsStatus()">重置所有</button>
    </div>
    <div style="margin-top: 20px;">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>id</th>
					<th>icon</th>
					<th>设备名</th>
                    <th>设备型号</th>
					<th>编号</th>
					<th>签借人</th>
					<th style="color:red;">所属</th>
					<th>借出时间</th>
					<th>确定</th>
					<th>重置</th>
				</tr>
			</thead>
			<tbody>
            {% for device in deviceobj %}
                <tr did="{{ device.id }}">
                    <td>{{forloop.counter}}</td>
                {% if device.dev_imgs_set.all.0.path == Null %}
                    <td></td>
                {% else %}
                    <td><img onclick="showDevInfo()" class="dev_icon" id="icon_{{ device.id }}" src="/media/{{device.dev_imgs_set.all.0.path}}"/></td>
                {% endif %}
                    <td>{{ device.device_name }}</td>
                    <td>{{ device.model }}</td>
                    <td>{{ device.theNum }}</td>
                {% if device.borrower %}
                    <td>{{ device.borrower }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                    <td>{{ device.owner }}</td>
                {% if device.borrow_time == Null %}
                    <td></td>
                {% else %}
                    <td>{{ device.borrow_time }}</td>
                {% endif %}
                {% if device.check_dev == '0'%}
                    <td><button type="button" class="btn btn-sm btn-success" onclick="confirmIsAt()" id="confirm1_{{ device.id }}">确定</button></td>
                    <td></td>
                {% elif device.check_dev == '1' %}
                    <td></td>
                    <td><button type="button" class="btn btn-sm btn-danger" onclick="initaillizeTheDev()" id="confirm0_{{ device.id }}">重置</button></td>
                {% endif %}
                 </tr>
            {% endfor %}

			</tbody>
		</table>
	</div>

</div>
		</div>
	</div>
</div>

{% endblock %}
{% block js %}
 <script src="{% static 'devMS/js/checkDevices/checkDevices.js' %}"></script>
{% endblock %}

templates/deviceInfo.html
{% extends "base.html"%}
{% load static %}
{% block title %}设备系统LOG{% endblock %}
{% block contend %}
    <link href="{% static "devMS/css/showDev/showDevInfoPage.css" %}" rel="stylesheet">
    <button type="button" class="btn btn-sm btn-success btn-back" onclick="javascript:history.back(-1);">《返回</button>
    <div id="show_dev_inifo_page_div">
        <table class="table table-bordered">
            <tr class="info_table">
                <td>设备id: {{ device.id }}</td>
                <td>设备名: {{ device.device_name }}</td>
                <td>设备型号: {{ device.model }}</td>
                <td>设备编号: {{ device.theNum }}</td>
                <td>借出时间: {{ device.borrow_time }}</td>
            </tr>
            <tr class="info_table">
                {% if device.status == '1' %}
                    <td>状态: 未借出</td>
                {% elif device.status == '2'%}
                    <td>状态: 已借出</td>
                {% endif %}
                <td>借阅者: {{ device.borrower }}</td>
                <td>所属:  {{ device.owner }}</td>
                <td>系统版本: {{ device.version }}</td>
                <td>添加时间: {{ device.add_time|date:"Y-m-d H:i:s" }}</td>
            </tr>

            <tr class="info_table">
                {% if  device.plateform == '1' %}
                    <td>平台: android</td>
                {% elif device.plateform == '2' %}
                    <td>平台: ios</td>
                {% endif %}
                <td>品牌: {{ device.brand }}</td>
                <td colspan="3">备注: {{ device.comments }} </td>
            </tr>
            <tr class="info_table">
                <td colspan="5">UUID: {{ device.UUID }}</td>
            </tr>
        </table>
    </div>
    <div style="width: 900px;margin-left: 140px">
    <table class="table table-bordered">
        <tr>
            <td>
                <strong>设备图片</strong>
            </td>
            <td>
            <div class="responsive" style="text-align:center;height:500px;">
            <img style="height:500px;" src="/media/{{device.dev_imgs_set.all.0.path}}">
            </div>
            </td>
        </tr>
        <tr>
            <td>
                <strong>申请采购图片</strong>
            </td>
            <td>
            <div class="responsive" style="text-align:center;height:500px;">
            <img style="height:500px;" src="/media/{{device.dev_imgs_set.all.0.apply_path}}">
            </div>
            </td>
        </tr>
    </table>
    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} 设备管理查询列表{% endblock %}
{% block link %}<link href="{% static 'devMS/css/showDev/showDevs.css' %}" rel="stylesheet">{% endblock %}
{% block contend %}

<div id="search_area">
{% include "search.html" %}
    <div>
        <table class="table table-striped" id="alldeviceInfo">
            <thead>
                <tr>
                    <th>id</th>
                    <th>icon</th>
                    <th>设备名</th>
                    <th>型号</th>
                    <th>编号</th>
                    <th>签借人</th>
                    <th>申请</th>
                    <th style="color:red;">所属</th>
                    <th>借出时间</th>
                </tr>
            </thead>
            <tbody>
            {% for device in deviceobj %}
                <tr did="{{ device.id }}">
                    <td>{{forloop.counter}}</td>
                {% if device.dev_imgs_set.all.0.path == Null %}
                    <td></td>
                {% else %}
                    <td><img onclick="showDevInfo()" class="dev_icon" id="icon_{{ device.id }}" src="/media/{{device.dev_imgs_set.all.0.path}}"/></td>
                {% endif %}
                    <td>{{ device.device_name }}</td>
                    <td>{{ device.model}}</td>
                    <td>{{ device.theNum }}</td>
                {% if device.borrower %}
                    <td>{{ device.borrower }}</td>
                    <td></td>
                {% else %}
                    <td><input type="text" class="form-control" style="width:150px;" name="browsser" id="#input_{{ device.id }}"></td>
                    <td><button class="btn btn-sm btn-success" dversion="{{ device.version }}" onclick="applyFor()" id={{ device.id }}>申 请</button></td>
                {% endif %}
                    <td>{{ device.owner }}</td>
                {% if device.borrow_time == Null %}
                    <td></td>
                {% else %}
                    <td>{{ device.borrow_time }}</td>
                {% endif %}
                 </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% include "page.html" %}
{% endblock %}

{% block js %}
 <script src="{% static 'devMS/js/showDev/showDevs.js' %}"></script>
 <script src="{% static 'devMS/js/exportExcel.js' %}"></script>
{% endblock %}

templates/log.html
{% extends "base.html"%}
{% load static %}
{% block title %}设备系统LOG{% endblock %}
{% block link %}<link href="{% static '/devMS/css/logMan/logMan.css'%}" rel="stylesheet">{% endblock %}

{% block contend %}
<div id="logPanel">
   {% for log in logobj %}
       <b><p style="margin:0px;color:#428BCA;display:inline;">{{ forloop.counter }}</p></b>
       <b><p style="margin:0px;_color:#428BCA;display:inline;">{{ log.1 }}</p></b></br>
   {% endfor %}
</div>
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页</title>
    <link href="/static/dist/css/signin.css" rel="stylesheet" type="text/css">
    <style>
        .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
  border: 2px;
  -moz-border-radius: 15px;
  -webkit-border-radius: 15px;
  border-radius:15px;
}
    </style>
</head>
<body style="background-color: #EEEEFF;">

    <div class="container">
        <div style=" max-width: 330px;padding: 15px;margin: 0 auto;font-size:16px">
           <h1 class="form-signin-heading">欢迎登录！</h1>
           <form action="/mobiledevice/login/" method="post">
                {% csrf_token %}
               <table>
                <tr><td>{{login_form.user_name.label}}</td>
                    <td>{{ login_form.user_name }}</td>
                </tr>
                <tr><td>{{ login_form.user_name.error_messages }}</td></tr>
                <tr><td>{{login_form.password.label}}</td>
                   <td>{{ login_form.password }}</td>
                </tr>
                <tr><td>{{ login_form.password.error_messages }}</td></tr>
                <tr>{{ error_message }}</tr>
               </table>
               <input type="submit" value="登录" class="button">
               <input type="button" value="注册" class="button" onclick="signup()">
           </form>
        </div>
    </div>
 <script src="{% static '/dist/js/signup.js' %}"></script>
</body>
</html>

templates/manadevice.html
{% extends "base.html" %}
{% load static %}
{% block title %}管理设备{% endblock %}
{% block link %}<link href="{% static 'devMS/css/manDevices/manDevices.css' %}" rel="stylesheet">{% endblock %}
{% block contend %}

<div id="search_area">
    {% include "search.html" %}
    <div>
		<table class="table table-striped">
			<thead>
				<tr>
				    <th>id</th>
					<th>icon</th>
					<th>设备名</th>
					<th>编号</th>
					<th>签借人</th>
					<th>操作</th>
					<th>删除</th>
					<th>修改</th>
					<th style="color:red;">所属</th>
					<th>借出时间</th>
				</tr>
			</thead>
			<tbody>
            {% for device in deviceobj %}
                <tr did="{{ device.id }}">
                    <td>{{forloop.counter}}</td>
                {% if device.dev_imgs_set.all.0.path == Null %}
                    <td></td>
                {% else %}
                    <td><img onclick="showDevInfo()" class="dev_icon" id="icon_{{ device.id }}" src="/media/{{device.dev_imgs_set.all.0.path}}"/></td>
                {% endif %}
                    <td>{{ device.device_name }}</td>
                    <td>{{ device.theNum }}</td>
                {% if device.borrower %}
                    <td>
                        <input type="text" class="form-control" style="width:130px;" value="{{ device.borrower }}" id="input_{{ device.id }}">
                        <button type="button" class="btn btn-sm btn-warning" style="margin-top:5px;"  onclick="applyFor()" id="{{ device.id }}" dversion="{{ device.version }}">修改</button>
                    </td>
                    <td><button class="btn btn-sm btn-danger" onclick="confirmReturned()" id="return_{{ device.id }}">归还</button></td>
                    <td><button type="button" class="btn btn-sm btn-danger" id="delete_{{ device.id }}" onclick="deleteDev()">删除</button></td>
                    <td><button type="button" class="btn btn-sm btn-warning" id="modify_{{ device.id }}" onclick="modifyDevice()">修改</button></td>
                {% else %}
                    <td><input type="text" class="form-control" style="width:130px;" name="browsser" id="input_{{ device.id }}"></td>
                    <td><button class="btn btn-sm btn-success" onclick="applyFor()" id="{{ device.id }}" dversion="{{ device.version }}">借出</button></td>
                    <td><button type="button" class="btn btn-sm btn-danger"id="delete_{{ device.id }}" onclick="deleteDev()">删除</button></td>
                    <td><button type="button" class="btn btn-sm btn-warning"  id="modify_{{ device.id }}" onclick="modifyDevice()">修改</button></td>
                {% endif %}
                    <td>{{ device.owner }}</td>
                {% if device.borrow_time == Null %}
                    <td></td>
                {% else %}
                    <td>{{ device.borrow_time }}</td>
                {% endif %}
                 </tr>
            {% endfor %}

			</tbody>
		</table>
	</div>
</div>
{% include "page.html" %}
{% endblock %}

{% block js %}
 <script src="{% static 'devMS/js/manDevices/manDevices.js' %}"></script>
 <script src="{% static 'devMS/js/exportExcel.js' %}"></script>
{% endblock %}

templates/modifydevice.html
{% extends "base.html" %}
{% load static %}
{% block title %} 设备管理修改页{% endblock %}
{% block contend %}
    <link href="{%static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{%static 'devMS/css/index.css'%}" rel="stylesheet">
    <link href="{%static 'devMS/css/manDevices/changeDevInfo.css'%}" rel="stylesheet"/>
    <div id="add_devices">
        <form action="/mobiledevice/manadevice/deviceid={{ deviceObj.id }}" method="post" enctype="multipart/form-data">
            <table>
               {{ deviceform.as_table }}
            </table>
{#            <p><img id="previewPic" style="margin-left:300px;width:250px;height: 300px" src="/media/{{ deviceObj.dev_imgs_set.all.0.path }}"></p>#}
             <p><img id="previewApplyPic" style="margin-left:300px;width:250px;height: 300px" src="/media/{{ path }}"></p>
            <p><img id="previewApplyPic" style="margin-left:300px;width:250px;height: 300px" src="/media/{{ deviceObj.dev_imgs_set.all.0.apply_path }}"></p>
            <p><input name="deviceid" type="text" value="{{ deviceObj.id }}" style="display: none"></p>
            <p style="margin-left:300px;"><input type="submit" value="修改" style="margin-left:10px;position:absolute;padding-top:5px;color: #2a6496">
                 <input type="button" value="返回" style="margin-left:200px;position:absolute;padding-top:5px;color: #2a6496" id="cancleModifyDev" ></p>
        </form>
    </div>
{% endblock %}
{% block js %}
 <script src="{% static 'devMS/js/modifyDevices/modifyDevices.js' %}"></script>
{% endblock %}

templates/page.html
<nav aria-label="Page navigation" style="margin-top: 900px ">
        <div class="pagination">
            <ul class="pagination">
            {% if deviceobj.has_previous %}
                <li><a href="{{deviceobj.previous_page_number}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span></a></li>
            {% endif %}

            {% for num in deviceobj.paginator.page_range%}
                {%if pindex == deviceobj.number%}
                    <li><a href="">{{ num }}</a></li>
                {%else%}
                    <li><a href="{{num}}">{{ num }}</a></li>
                {%endif%}
             {% endfor %}

             {% if deviceobj.has_next %}
                 <li><a href="{{deviceobj.next_page_number}}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span></a></li>
              {% endif %}
            </ul>
        </div>
    </nav>

templates/search.html
<div>
    <table _border="1" style="width:100%;height:100px;margin-left:20px;">
        <tr>
            <td style="width:33%;">
              <label class="label_style">{{ searchDeviceform.plateform.label }}</label>
               {{ searchDeviceform.plateform}}
            </td>
            <td style="width:33%;">
                <label class="label_style">{{ searchDeviceform.brand.label }}</label>
               {{ searchDeviceform.brand }}
            </td>
            <td style="width:33%;">
                <label class="label_style">{{ searchDeviceform.version.label }}</label>
                {{ searchDeviceform.version}}
            </td>
        </tr>
        <tr>
            <td>
                <label class="label_style" >{{ searchDeviceform.status.label }}</label>
                {{ searchDeviceform.status }}
            </td>
            <td>
                <label class="label_style" >{{ searchDeviceform.category.label }}</label>
                {{ searchDeviceform.category }}
            </td>
            <td>
                 <label class="label_style" >{{ searchDeviceform.borrower.label }}</label>
                {{ searchDeviceform.borrower }}
            </td>
        </tr>
    </table>
</div>
<div>
    <button class="btn btn-primary" style="width:100px;" id="search_btn" onclick="searchDevs()">查 询</button>
    <button class="btn btn-primary" style="width:100px;margin-top:20px;" id="export_btn" onclick="exportDevs({{deviceInfo}})">导 出</button>
</div>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body style="background-color: #EEEEFF;">
 <link href="{% static "/dist/css/signin.css" %}" rel="stylesheet">
 <div class="container">
     <div style=" max-width: 330px;padding: 15px;margin: 0 auto;font-size:16px">
           <h1>欢迎注册！</h1>
            <form action="/mobiledevice/signup/" method="post">
                <table>
                    <tr>
                        <td>{{ signup_form.user_name.label}}</td>
                        <td>{{ signup_form.user_name }}</td>
                    </tr>
                    <tr><td>{{ signup_form.user_name.error_messages }}</td></tr>
                    <tr>
                        <td>{{ signup_form.login_name.label}}</td>
                        <td>{{ signup_form.login_name }}</td>

                    </tr>
                    <tr><td>{{ signup_form.login_name.error_messages }}</td></tr>
                    <tr>
                        <td>{{ signup_form.password.label }}</td>
                        <td>{{ signup_form.password }}</td>
                    </tr>
                    <tr> <td>{{ signup_form.password.error_messages }}</td></tr>
                    <tr>
                        <td>{{ signup_form.repassword.label}}</td>
                        <td>{{ signup_form.repassword }}</td>
                    </tr>
                    <tr><td>{{ signup_form.repassword.error_messages }}</td></tr>
                    <tr>{{ error_message }}</tr>
                </table>
                <input type="submit" value="注册" class="button">
           </form>
     </div>
    </div>
 <script src="{% static '/dist/js/signup.js' %}"></script>
</body>
</html>